---
- name: The play name
  hosts: Taipei
  gather_facts: true
  tasks:
    - name: The task name
      yum:
        name: httpd
        state: latest
      when: ansidble_facts['ansible_distribution']=="RedHat" 
